ccflags-y += -Idrivers/media/platform/msm/camera/camera-driver
ccflags-y += -Idrivers/media/platform/msm/camera/camera-driver/common
ccflags-y += -Idrivers/media/platform/msm/camera/camera-driver/sensor/io
obj-$(CONFIG_MSM_CSIPHY) += msm_csiphy.o
