ccflags-y += -Idrivers/media/platform/msm/camera/camera-driver
ccflags-y += -Idrivers/media/platform/msm/camera/camera-driver/common
ccflags-y += -Idrivers/media/platform/msm/camera/camera-driver/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera/camera-driver/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_ois.o
